#Graphic Engine
def Print_Img(img_name):
  if img_name == "Cave_Enter":
    print('')
    print('You found the entrance to the cave!')
    print('')
    print('.......................................')
    print('.............________..................')
    print('.........../          \................')
    print('........../            \...............')
    print('........./              \..............')
    print('......../       __       \.............')
    print('......./       /##\       \............')
    print('....../       |####|       \...........')
    print('...../________|####|________\..........')
    print('.......................................')
    
  elif img_name == "Cave_shop":
    print('                                       ')
    print('       You found a hidden Shop         ')
    print('                                       ')
    print('.......................................')
    print('...............______..................')
    print('............\ /       \ /..............')
    print('........... /-         -\..............')
    print('...........|    _        |.............')
    print("...........|   '^'       |.............")
    print('...........| ^-{ }-8   $_|.............')
    print('...........|   ( )     _\|.............')
    print('...........|__/___\___|__|.............')
    print('.......................................')

  elif img_name == "Cave_tunnel":
    print('                                       ')
    print('       You found a new tunnel          ')
    print('                                       ')
    print('.......................................')
    print('...............______..................')
    print('............\ /       \ /..............')
    print('........... /-         -\..............')
    print('...........|             |.............')
    print('...........|             |.............')
    print('...........|             |.............')
    print('...........|             |.............')
    print('...........|_____________|.............')
    print('.......................................')

  elif img_name == "Cave_Wall":
    print('                                       ')
    print('      You have ran into a wall         ')
    print('                                       ')
    print('.......................................')
    print('...............______..................')
    print('............\ /#######\ /..............')
    print('........... /-#########-\..............')
    print('...........|#############|.............')
    print('...........|#############|.............')
    print('...........|#############|.............')
    print('...........|#############|.............')
    print('...........|#############|.............')
    print('.......................................')

  elif img_name == "King":
    print("                      +                ")
    print("                     vAv .-.           ")
    print('                     (")| # |          ')
    print("                    / v \\# | + o      ")
    print("                   c\\  //=.-'O/\"-.   ")
    print('                   |/~."|  |"-/.-\'|   ')
    print("                   / .  (__|   |  |    ")
    print("                  (=/===)`  ~-.|.-'    ")                   

  elif img_name == "Fin":
    print("              _          _                          ")
    print("             | |_ ___   | |__   ___                 ")
    print("             | __/ _ \  | '_ \ / _ \                ")
    print("             | || (_) | | |_) |  __/                ")
    print("              \__\___/  |_.__/ \___|                ")
    print("                 _   _                          _   ")
    print("   ___ ___  _ __ | |_(_)_ __  _   _  ___ ___  __| | ")
    print("  / __/ _ \| '_ \| __| | '_ \| | | |/ __/ _ \/ _` | ")
    print(" | (_| (_) | | | | |_| | | | | |_| | (_|  __/ (_| | ")
    print("  \___\___/|_| |_|\__|_|_| |_|\__,_|\___\___|\__,_| ")               

  elif img_name == "Castle":
    print("                        _              ")
    print("                       /^\             ")
    print("                       | |             ")
    print("                   _   |-|             ")
    print("            _    _/^\_ | |             ")
    print("           /^\  / [_] \+-+             ")
    print("   _      |---||-------| |_       _    ")
    print(" _/^\_    _/^\_|  [_]  |_/^\_   _/^\_  ")
    print(" |!_!|    |!_!||_______||!_!|   |!_!|  ")
    print("  | |======| |===========| |=====| |   ")
    print("  |!|      | |    /^\    | |     |!|   ")
    print("  | |      |!|   |   |   |!|     | |   ")
    print("  |_|______|_|__ |   |___|_|_____|_|   ")
 
  elif img_name == "Logo":
    print("                      ,     \    /      ,                     ")
    print("                     / \    )\__/(     / \                    ")
    print("                    /   \  (_\  /_)   /   \                   ")
    print(" __________________/_____\__\@  @/___/_____\_________________ ")
    print(" |            ____          |\../|        _                 | ")
    print(" |           |  _ \          \VV/        (_)                | ")
    print(" |           | |_) | __ ___   ____ _ _ __ _  __ _           | ")
    print(" |           |  _ < / _` \ \ / / _` | '__| |/ _` |          | ")
    print(" |           | |_) | (_| |\ V / (_| | |  | | (_| |          | ")
    print(" |           |____/ \__,_| \_/ \__,_|_|  |_|\__,_|          | ")
    print(" |__________________________________________________________| ")
    print("             |    /\ /      \\       \ /\    |                ")
    print("             |  /   V        ))       V   \  |                ")
    print("             |/     `       //        '     \|                ")
    print("             `              V                '                ")

  elif img_name == "Cave_fairy":
    print('')
    print(    'You have discovered a magical fairy')
    print('')
    print(''' **You drink from the fairy\'s fountain
        and feel refreshed**''')
    print('.......................................')
    print('...|               *              |....')
    print('...|     *                        |....')
    print('...|     ___    hey!              |....')
    print('...| * ໒(ಠ_ಠ)७    listen!         |....')
    print('...|     /-\    *                 |....')
    print('...|                    _^|^_     |....')    
    print('...|  *  _____________ |_???_|    |....')
    print('.......................................')

  elif img_name == "Cave_Door":
    print('')
    print('       You have found a door           ')
    print('     ***The door is locked***          ')
    print('.......................................')
    print('............._________.................')
    print('............|*********|................')
    print('............|*********|................')
    print('............|*********|................')
    print('............|*******0*|................')
    print('............|*********|................')
    print('............|*********|................')
    print('............|_________|................')
    print('.......................................')

  elif img_name == "Boss_Door":
      print('')
      print('   You have found a creepy door        ')
      print('     ***The door is locked***          ')
      print('.......................................')
      print('............._________.................')
      print('............|         |................')
      print('............|   ???   |................')
      print('............|  ?___?  |................')
      print('............|  / * \  |................')
      print('............|  \_µ_/  |................')
      print('............|         |................')
      print('............|_________|................')
      print('.......................................')

  elif img_name == "Boss_Door_Unlocked":
      print('')
      print('   You have found a creepy door        ')
      print(' **You use the skull key to open it**  ')
      print('.......................................')
      print('............._________.................')
      print('............|         |................')
      print('............|   ???   |................')
      print('............|  ?___?  |................')
      print('............|  / * \  |................')
      print('............|  \_µ_/  |................')
      print('............|         |................')
      print('............|_________|................')
      print('.......................................')

  elif img_name == "Boss_Killed":
    print('                                       ')
    print('                                       ')
    print('                                       ')
    print('.......................................')
    print('...............______..................')
    print('............\ /       \ /..............')
    print('........... /-         -\..............')
    print('...........|    ______   |.............')
    print('...........|   |      |  |.............')
    print('...........|_  |  &&  | _|.............')
    print('...........|@@\   __  /@@|.............')
    print('...........|@@|__|__|_|@@|.............')
    print('.......................................')

  elif img_name == "Cave_Door_Unlocked":
    print('')
    print('       You have found a door           ')
    print('  ***You use your key to open it***    ')
    print('.......................................')
    print('............._________.................')
    print('............|*********|................')
    print('............|*********|................')
    print('............|*********|................')
    print('............|*******0*|................')
    print('............|*********|................')
    print('............|*********|................')
    print('............|_________|................')
    print('.......................................')

  elif img_name == "Cave_box":
    print('')
    print('    You have found a treasure chest    ')
    print('                                       ')
    print('.......................................')
    print('..........___________________..........')
    print('......../                     \........')
    print('.......|                       |.......')
    print('.......|        _______        |.......')
    print('.......|       /       \       |.......')
    print('.......|       \_$$$$$_/       |.......')
    print('.......|       |       |       |.......')
    print('.......|       |__&&___|       |.......')
    print('........-----------------------........')
    print('.......................................')

  elif img_name == "Goblin":
    print('')
    print('.......................................')
    print(f' Lvl: {Calradia.enemy.lvl}   Name: {Calradia.enemy.mName}   ')
    print(f'       Health {Calradia.enemy.health} ')
    print('..........___________________..........')
    print('......../                     \........')
    print('.......|          , ,          |.......')
    print('.......|         (ʘдʘ)  W      |.......')
    print('.......|      d--->|<---|      |.......')
    print('.......|          |||   |      |.......')
    print('.......|          )|(          |.......')
    print('.......|        _/   \_        |.......')
    print('........-----------------------........')
    print('.......................................')

  elif img_name == "Spider":
    print('')
    print('.......................................')
    print(f' Lvl: {Calradia.enemy.lvl}   Name: {Calradia.enemy.mName}   ')
    print(f'       Health {Calradia.enemy.health} ')
    print('.......................................')
    print('.......-------------------------.......')
    print('...../                           \.....')
    print('....|                             |....')
    print('....|                             |....')
    print('....|        _ _ _ _ _ _ _        |....')
    print('....| ミ /╲/( ͜。 ͜͡     )/\╱\   |....')
    print('....|   / /\              / /\ \  |....')
    print('....|_____________________________|....')
    print('.......................................')

  elif img_name == "Boss":
    print('')
    print('.......................................')
    print(f' Lvl: {Calradia.enemy.lvl}   Name: {Calradia.enemy.mName}   ')
    print(f'       Health {Calradia.enemy.health} ')
    print('                                       ')
    print('.......................................')
    print('........._____________________.........')
    print('......./           ,w,         \.......')
    print('......|           (ʘдʘ)   {#}   |......')
    print('......|      d--->(|||)<---|    |......')
    print('......|           (|||)    |    |......')
    print('......|           /   \    |    |......')
    print('......|         _/     \_       |......')
    print('.......-------------------------.......')
    print('.......................................')

  elif img_name == "Stats":
    print(f' Position {Calradia.position}')
    print('.......................................')
    print(f' Name : {Calradia.player.pname}   Class: {Calradia.player.pclass}     Lvl: {Calradia.player.lvl}')
    #If player is a mage show their MP
    if Calradia.player.pclass == "Mage":
      print(f' HP: {Calradia.player.health}/{Calradia.player.max_health}      MP: {Calradia.player.mp}/{Calradia.player.max_mp} ')
    else:
      print(f' HP: {Calradia.player.health}/{Calradia.player.max_health} ')
    print('.......................................')
    #player has a weapon equiped
    print(f' Weapon: {Calradia.player.Weapon[0].wname}   Dmg: {Calradia.player.Weapon[0].watk}')

    #Block% = (5+Evasion) - Armor Rating
    #Crit% = 100-((5 + Evasion)- Armor Weight)
    #Miss% = Player Accuracy
    #Hit% = (Weapon Hit rate * Player Accuracy)* 0.3

    cng_block = int(((5+Calradia.player.Evasion)+Calradia.player.Armor[0].arate))
    cng_crit = int(((5+Calradia.player.Evasion)-Calradia.player.Armor[0].aweight)*0.5)
    cng_miss = int(Calradia.player.Accuracy)
    cng_hit = int(((Calradia.player.Weapon[0].w_hit*Calradia.player.Accuracy)*0.3))
    print('.......................................')

    print(f' Block%: {cng_block}     Crit%: {cng_crit}   ')
    print(f" Miss%: {cng_miss}       Hit%: {cng_hit}")
    print('.......................................')
    print(f' Armor: {Calradia.player.Armor[0].aname}     Def Rating: {Calradia.player.Armor[0].arate}')
    print('.......................................')
    #Check for items in the Inventory
    print(" Inventory:")
    if len(Calradia.player.inv) > 0:
      for item in Calradia.player.inv:
        print(f' {item.iname}     {item.iamount}')
    else:
      print(" You don't have any items")
    print('.......................................')

    #Check for Spells
    print(" Spells:")
    if len(Calradia.player.Spells) > 0:
      for spell in Calradia.player.Spells:
        print(f' {spell.sname}     Lvl: {spell.slevel}    Dmg: {spell.sDmg}')
    else:
      print(" You don't have any Spells")
    print('.......................................')
    print('')
